# -*- coding: utf-8 -*-
"""Python_ML_Project_Bootcamp_Project.ipynb

Automatically generated by Colaboratory.

# Importing libraries
"""

import numpy as np
import pandas as pd # Data Manipulation, Data Cleaning, Data Exploration, Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

"""# Importing dataset"""

df = pd.read_csv("/content/sample_data/Housing.csv")

df

df.info()

#    total values (entries) - non-null values = null values
#    545 - 545 = 0,   so zero null values in dataset

# null data checking 
df.isnull()

df.isnull().any()   # it rturn bool value

df.head(10)

df.tail(10)

# creating mapping 
# converting string value to numerical value

dataMappingMainroad = {
    "yes": 1,
    "no": 0
    
}

dataMappingGuestroom = {
    "yes": 1,
    "no": 0
    
}

dataMappingBasement = {
    "yes": 1,
    "no": 0
}

dataMappingHotwaterheating = {
    "yes": 1,
    "no": 0    
}

dataMappingAirconditioning = {
    "yes": 1,
    "no": 0   

    
}


dataMappingPrefarea = {
    "yes": 1,
    "no": 0

}

dataMappingFurnishingstatus = {
    
    "furnished": 3,
    "semi-furnished": 2,
    "unfurnished": 0
    
}

df['numMainroad'] = df['mainroad'].map(dataMappingMainroad)
df['numGuestroom'] = df['guestroom'].map(dataMappingGuestroom)
df['numBasement'] = df['basement'].map(dataMappingBasement)

df['numHotwaterheating'] = df['hotwaterheating'].map(dataMappingHotwaterheating)
df['numAirconditioning'] = df['airconditioning'].map(dataMappingAirconditioning)
df['numPrefarea'] = df['prefarea'].map(dataMappingPrefarea)

df['numFurnishingStatus'] = df['furnishingstatus'].map(dataMappingFurnishingstatus)

df

df.shape      # rtuen no. of rows and columns

df.describe()

df.columns    # it retuns colmns title name

df['price'].isnull().any()

df['area'].isnull().any()

df['bedrooms'].isnull().any()

df['bathrooms'].isnull().any()

df['stories'].isnull().any()

df['mainroad'].isnull().any()

df['guestroom'].isnull().any()

df['basement'].isnull().any()

df['hotwaterheating'].isnull().any()

df['airconditioning'].isnull().any()

df['parking'].isnull().any()

df['prefarea'].isnull().any()

df['furnishingstatus'].isnull().any()

df['numGuestroom'].isnull().any()

df['numBasement'].isnull().any()

df['numHotwaterheating'].isnull().any()

df['numAirconditioning'].isnull().any()

df['numPrefarea'].isnull().any()

df['numFurnishingStatus'].isnull().any()


